apiVersion: pihole.paldab.nl/v1alpha1
kind: PiHoleCluster
metadata:
  name: test-pihole
spec:
  image: pihole/pihole:latest
  existingAdminPasswordSecret: pihole-admin-password
  timezone: Europe/Amsterdam
  storage:
    size: 3Gi

  dnsUpstreams:
    - 8.8.8.8
    - 8.8.4.4

---
apiVersion: v1
stringData:
  password: "admin"
kind: Secret
metadata:
  name: pihole-admin-password-test
type: Opaque
