apiVersion: pihole.paldab.nl/v1alpha1
kind: PiHoleCluster
metadata:
  name: minimal-pihole
spec:
  replicas: 3

  existingSecretRef:
    secretName: advanced-pihole-admin-password
    passwordKey: password

  image: pihole/pihole:2026.05.0

  storage:
    size: 5Gi

  config:
    TZ: Europe/Amsterdam
    FTLCONF_dns_listeningMode: all
