apiVersion: pihole.paldab.nl/v1alpha1
kind: PiHoleCluster
metadata:
  name: test-pihole
spec:
  replicas: 3

  image: pihole/pihole:latest

  existingSecretRef:
    secretName: pihole-admin-password-test

  timezone: Europe/Amsterdam

  storage:
    size: 5Gi
---
apiVersion: v1
stringData:
  password: "admin"
kind: Secret
metadata:
  name: pihole-admin-password-test
type: Opaque
