//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in AdList) DeepCopyInto(out *AdList) {
	{
		in := &in
		*out = make(AdList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AdList.
func (in AdList) DeepCopy() AdList {
	if in == nil {
		return nil
	}
	out := new(AdList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in CNAMERecords) DeepCopyInto(out *CNAMERecords) {
	{
		in := &in
		*out = make(CNAMERecords, len(*in))
		for key, val := range *in {
			var outVal []CanonicalName
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]CanonicalName, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CNAMERecords.
func (in CNAMERecords) DeepCopy() CNAMERecords {
	if in == nil {
		return nil
	}
	out := new(CNAMERecords)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterRef) DeepCopyInto(out *ClusterRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterRef.
func (in *ClusterRef) DeepCopy() *ClusterRef {
	if in == nil {
		return nil
	}
	out := new(ClusterRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in CustomOptions) DeepCopyInto(out *CustomOptions) {
	{
		in := &in
		*out = make(CustomOptions, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomOptions.
func (in CustomOptions) DeepCopy() CustomOptions {
	if in == nil {
		return nil
	}
	out := new(CustomOptions)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExistingPasswordSecretRef) DeepCopyInto(out *ExistingPasswordSecretRef) {
	*out = *in
	if in.PasswordKey != nil {
		in, out := &in.PasswordKey, &out.PasswordKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExistingPasswordSecretRef.
func (in *ExistingPasswordSecretRef) DeepCopy() *ExistingPasswordSecretRef {
	if in == nil {
		return nil
	}
	out := new(ExistingPasswordSecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalStatisticsConfig) DeepCopyInto(out *ExternalStatisticsConfig) {
	*out = *in
	out.Database = in.Database
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalStatisticsConfig.
func (in *ExternalStatisticsConfig) DeepCopy() *ExternalStatisticsConfig {
	if in == nil {
		return nil
	}
	out := new(ExternalStatisticsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExternalStatisticsStatus) DeepCopyInto(out *ExternalStatisticsStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExternalStatisticsStatus.
func (in *ExternalStatisticsStatus) DeepCopy() *ExternalStatisticsStatus {
	if in == nil {
		return nil
	}
	out := new(ExternalStatisticsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in HostRecords) DeepCopyInto(out *HostRecords) {
	{
		in := &in
		*out = make(HostRecords, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HostRecords.
func (in HostRecords) DeepCopy() HostRecords {
	if in == nil {
		return nil
	}
	out := new(HostRecords)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in List) DeepCopyInto(out *List) {
	{
		in := &in
		*out = make(List, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new List.
func (in List) DeepCopy() List {
	if in == nil {
		return nil
	}
	out := new(List)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleCluster) DeepCopyInto(out *PiHoleCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleCluster.
func (in *PiHoleCluster) DeepCopy() *PiHoleCluster {
	if in == nil {
		return nil
	}
	out := new(PiHoleCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiHoleCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleClusterList) DeepCopyInto(out *PiHoleClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PiHoleCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleClusterList.
func (in *PiHoleClusterList) DeepCopy() *PiHoleClusterList {
	if in == nil {
		return nil
	}
	out := new(PiHoleClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiHoleClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleClusterSpec) DeepCopyInto(out *PiHoleClusterSpec) {
	*out = *in
	in.ExistingSecretRef.DeepCopyInto(&out.ExistingSecretRef)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(PiholePodStorage)
		(*in).DeepCopyInto(*out)
	}
	if in.TimeZone != nil {
		in, out := &in.TimeZone, &out.TimeZone
		*out = new(string)
		**out = **in
	}
	if in.DNSUpstreams != nil {
		in, out := &in.DNSUpstreams, &out.DNSUpstreams
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Config != nil {
		in, out := &in.Config, &out.Config
		*out = new(PiHolePodConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Services != nil {
		in, out := &in.Services, &out.Services
		*out = new(PiHoleServiceSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Ingress != nil {
		in, out := &in.Ingress, &out.Ingress
		*out = new(PiHoleIngressSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Statistics != nil {
		in, out := &in.Statistics, &out.Statistics
		*out = new(StatisticsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleClusterSpec.
func (in *PiHoleClusterSpec) DeepCopy() *PiHoleClusterSpec {
	if in == nil {
		return nil
	}
	out := new(PiHoleClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleClusterStatus) DeepCopyInto(out *PiHoleClusterStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.CurrentLeader != nil {
		in, out := &in.CurrentLeader, &out.CurrentLeader
		*out = new(string)
		**out = **in
	}
	if in.FailoverInProgress != nil {
		in, out := &in.FailoverInProgress, &out.FailoverInProgress
		*out = new(bool)
		**out = **in
	}
	in.Statistics.DeepCopyInto(&out.Statistics)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleClusterStatus.
func (in *PiHoleClusterStatus) DeepCopy() *PiHoleClusterStatus {
	if in == nil {
		return nil
	}
	out := new(PiHoleClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleConfig) DeepCopyInto(out *PiHoleConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleConfig.
func (in *PiHoleConfig) DeepCopy() *PiHoleConfig {
	if in == nil {
		return nil
	}
	out := new(PiHoleConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiHoleConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleConfigList) DeepCopyInto(out *PiHoleConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]PiHoleConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleConfigList.
func (in *PiHoleConfigList) DeepCopy() *PiHoleConfigList {
	if in == nil {
		return nil
	}
	out := new(PiHoleConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *PiHoleConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleConfigSpec) DeepCopyInto(out *PiHoleConfigSpec) {
	*out = *in
	out.ClusterRef = in.ClusterRef
	if in.Adlists != nil {
		in, out := &in.Adlists, &out.Adlists
		*out = make(AdList, len(*in))
		copy(*out, *in)
	}
	if in.Denylist != nil {
		in, out := &in.Denylist, &out.Denylist
		*out = make(List, len(*in))
		copy(*out, *in)
	}
	if in.Allowlist != nil {
		in, out := &in.Allowlist, &out.Allowlist
		*out = make(List, len(*in))
		copy(*out, *in)
	}
	if in.Regexlist != nil {
		in, out := &in.Regexlist, &out.Regexlist
		*out = make(RegexList, len(*in))
		copy(*out, *in)
	}
	if in.CNAMEs != nil {
		in, out := &in.CNAMEs, &out.CNAMEs
		*out = make(CNAMERecords, len(*in))
		for key, val := range *in {
			var outVal []CanonicalName
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make([]CanonicalName, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.Hosts != nil {
		in, out := &in.Hosts, &out.Hosts
		*out = make(HostRecords, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.CustomOptions != nil {
		in, out := &in.CustomOptions, &out.CustomOptions
		*out = make(CustomOptions, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleConfigSpec.
func (in *PiHoleConfigSpec) DeepCopy() *PiHoleConfigSpec {
	if in == nil {
		return nil
	}
	out := new(PiHoleConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleConfigStatus) DeepCopyInto(out *PiHoleConfigStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleConfigStatus.
func (in *PiHoleConfigStatus) DeepCopy() *PiHoleConfigStatus {
	if in == nil {
		return nil
	}
	out := new(PiHoleConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleIngressSpec) DeepCopyInto(out *PiHoleIngressSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.ClassName != nil {
		in, out := &in.ClassName, &out.ClassName
		*out = new(string)
		**out = **in
	}
	if in.TLS != nil {
		in, out := &in.TLS, &out.TLS
		*out = new(PiHoleIngressTLS)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleIngressSpec.
func (in *PiHoleIngressSpec) DeepCopy() *PiHoleIngressSpec {
	if in == nil {
		return nil
	}
	out := new(PiHoleIngressSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleIngressTLS) DeepCopyInto(out *PiHoleIngressTLS) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleIngressTLS.
func (in *PiHoleIngressTLS) DeepCopy() *PiHoleIngressTLS {
	if in == nil {
		return nil
	}
	out := new(PiHoleIngressTLS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHolePodConfig) DeepCopyInto(out *PiHolePodConfig) {
	*out = *in
	if in.Labels != nil {
		in, out := &in.Labels, &out.Labels
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Env != nil {
		in, out := &in.Env, &out.Env
		*out = make([]v1.EnvVar, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]v1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	in.Resources.DeepCopyInto(&out.Resources)
	if in.Probes != nil {
		in, out := &in.Probes, &out.Probes
		*out = new(Probes)
		(*in).DeepCopyInto(*out)
	}
	if in.SecurityContext != nil {
		in, out := &in.SecurityContext, &out.SecurityContext
		*out = new(v1.SecurityContext)
		(*in).DeepCopyInto(*out)
	}
	if in.PodSecurityContext != nil {
		in, out := &in.PodSecurityContext, &out.PodSecurityContext
		*out = new(v1.PodSecurityContext)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHolePodConfig.
func (in *PiHolePodConfig) DeepCopy() *PiHolePodConfig {
	if in == nil {
		return nil
	}
	out := new(PiHolePodConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiHoleServiceSpec) DeepCopyInto(out *PiHoleServiceSpec) {
	*out = *in
	if in.Web != nil {
		in, out := &in.Web, &out.Web
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.DHCP != nil {
		in, out := &in.DHCP, &out.DHCP
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiHoleServiceSpec.
func (in *PiHoleServiceSpec) DeepCopy() *PiHoleServiceSpec {
	if in == nil {
		return nil
	}
	out := new(PiHoleServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PiholePodStorage) DeepCopyInto(out *PiholePodStorage) {
	*out = *in
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		x := (*in).DeepCopy()
		*out = &x
	}
	if in.StorageClass != nil {
		in, out := &in.StorageClass, &out.StorageClass
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PiholePodStorage.
func (in *PiholePodStorage) DeepCopy() *PiholePodStorage {
	if in == nil {
		return nil
	}
	out := new(PiholePodStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Probes) DeepCopyInto(out *Probes) {
	*out = *in
	if in.Startup != nil {
		in, out := &in.Startup, &out.Startup
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Readiness != nil {
		in, out := &in.Readiness, &out.Readiness
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.Liveness != nil {
		in, out := &in.Liveness, &out.Liveness
		*out = new(v1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Probes.
func (in *Probes) DeepCopy() *Probes {
	if in == nil {
		return nil
	}
	out := new(Probes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in RegexList) DeepCopyInto(out *RegexList) {
	{
		in := &in
		*out = make(RegexList, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RegexList.
func (in RegexList) DeepCopy() RegexList {
	if in == nil {
		return nil
	}
	out := new(RegexList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfig) DeepCopyInto(out *ServiceConfig) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(v1.ServiceType)
		**out = **in
	}
	if in.NodePort != nil {
		in, out := &in.NodePort, &out.NodePort
		*out = new(int32)
		**out = **in
	}
	if in.LoadBalancerIP != nil {
		in, out := &in.LoadBalancerIP, &out.LoadBalancerIP
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfig.
func (in *ServiceConfig) DeepCopy() *ServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatisticsDatabaseSpec) DeepCopyInto(out *StatisticsDatabaseSpec) {
	*out = *in
	out.SecretRef = in.SecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatisticsDatabaseSpec.
func (in *StatisticsDatabaseSpec) DeepCopy() *StatisticsDatabaseSpec {
	if in == nil {
		return nil
	}
	out := new(StatisticsDatabaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatisticsSpec) DeepCopyInto(out *StatisticsSpec) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalStatisticsConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatisticsSpec.
func (in *StatisticsSpec) DeepCopy() *StatisticsSpec {
	if in == nil {
		return nil
	}
	out := new(StatisticsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatisticsStatus) DeepCopyInto(out *StatisticsStatus) {
	*out = *in
	if in.External != nil {
		in, out := &in.External, &out.External
		*out = new(ExternalStatisticsStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatisticsStatus.
func (in *StatisticsStatus) DeepCopy() *StatisticsStatus {
	if in == nil {
		return nil
	}
	out := new(StatisticsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StatsDatabaseSecretSelector) DeepCopyInto(out *StatsDatabaseSecretSelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StatsDatabaseSecretSelector.
func (in *StatsDatabaseSecretSelector) DeepCopy() *StatsDatabaseSecretSelector {
	if in == nil {
		return nil
	}
	out := new(StatsDatabaseSecretSelector)
	in.DeepCopyInto(out)
	return out
}
