name: Build and push images

on:
  push:
    tags:
      - "v*.*.*" # semver

jobs:
  e2e:
    uses: ./.github/workflows/test-e2e.yml
    with:
      version: ${{ github.ref_name }}

  push_to_registry:
    needs: e2e
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v4
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build docker image
        run: make docker-build-all \
          VERSION=${{ github.ref_name }} \
          GIT_COMMIT=${{ github.sha }}

      - name: Build docker image
        run: make docker-push-all \
          VERSION=${{ github.ref_name }} \
          GIT_COMMIT=${{ github.sha }}
